#!/usr/bin/env python3
"""Regenerates Sources/Data/MoveText.swift: each move's Korean description (PokeAPI move_flavor_text, language 3), the earliest Korean
games first (X·Y, then OR·AS, S·M, US·UM, LGPE, SwSh) — the closest to Gen IV's rules there is. Run from the repo root: python3 tools/gen-movetext.py"""
import csv, io, urllib.request
API = 'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/'
def rows(name): return list(csv.DictReader(io.StringIO(urllib.request.urlopen(API + name + '.csv').read().decode('utf-8'))))
order = ['x-y', 'omega-ruby-alpha-sapphire', 'sun-moon', 'ultra-sun-ultra-moon', 'lets-go-pikachu-lets-go-eevee', 'sword-shield']
vg = {r['id']: r['identifier'] for r in rows('version_groups')}
best = {}
for r in rows('move_flavor_text'):
    g = vg.get(r['version_group_id'])
    if r['language_id'] != '3' or g not in order: continue
    m = int(r['move_id'])
    if m > 467: continue                                                  # Gen IV's moves
    text = ' '.join(r['flavor_text'].replace('­', '').split())
    if m not in best or order.index(g) < best[m][0]: best[m] = (order.index(g), text)
lines = [best.get(i, (0, ''))[1] for i in range(468)]
assert all('\\' not in t and '"""' not in t for t in lines)
out = ['// Generated by tools/gen-movetext.py (PokeAPI move_flavor_text: Korean, X·Y first). Do not edit by hand.', '',
       "/// A move's description in Korean (기술 바꾸기, the battle's move menu); nil = none.",
       'func moveText(_ id: Int) -> String? { id > 0 && id < moveTextLines.count && !moveTextLines[id].isEmpty ? String(moveTextLines[id]) : nil }',
       'private let moveTextLines = moveTextBlob.split(separator: "\\n", omittingEmptySubsequences: false)',
       'private let moveTextBlob = """'] + lines + ['"""', '']
open('Sources/Data/MoveText.swift', 'w').write('\n'.join(out))
print(sum(1 for t in lines[1:] if t), 'of 467 moves described')
